-- Copyright (c) 2026 Bob Hablutzel. All rights reserved.
--
-- Licensed under a dual-license model: freely available for non-commercial use;
-- commercial use requires a separate license. See LICENSE file for details.
-- Contact license@geastalt.com for commercial licensing.

-- Create addresses table (international address model)
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.addresses (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locality             VARCHAR(255),
    administrative_area  VARCHAR(100),
    postal_code          VARCHAR(20),
    country_code         VARCHAR(2),
    sub_locality         VARCHAR(255),
    sorting_code         VARCHAR(20),
    validated            BOOLEAN NOT NULL DEFAULT false
);

-- Create index for deduplication lookups
CREATE INDEX IF NOT EXISTS idx_addresses_lookup
ON public.addresses(
    COALESCE(locality, ''),
    COALESCE(administrative_area, ''),
    COALESCE(postal_code, ''),
    COALESCE(country_code, '')
);

-- Create address_lines table (1-many relationship with addresses)
CREATE TABLE IF NOT EXISTS public.address_lines (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_id    BIGINT NOT NULL REFERENCES public.addresses(id) ON DELETE CASCADE,
    line_order    INTEGER NOT NULL,
    line_value    VARCHAR(255) NOT NULL,
    UNIQUE (address_id, line_order)
);

CREATE INDEX IF NOT EXISTS idx_address_lines_address_id ON public.address_lines(address_id);

-- Add comments for documentation
COMMENT ON TABLE public.addresses IS 'International postal addresses';
COMMENT ON TABLE public.address_lines IS 'Address line components (street, secondary, etc.)';
