-- Create standardized_addresses table
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.standardized_addresses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street_address    VARCHAR(255),
    secondary_address VARCHAR(255),
    city              VARCHAR(255),
    state             VARCHAR(50),
    zip_code          VARCHAR(10),
    zip_plus4         VARCHAR(10)
);

-- Create unique index to prevent duplicates
CREATE UNIQUE INDEX IF NOT EXISTS idx_standardized_addresses_unique
ON public.standardized_addresses(
    COALESCE(street_address, ''),
    COALESCE(secondary_address, ''),
    COALESCE(city, ''),
    COALESCE(state, ''),
    COALESCE(zip_code, ''),
    COALESCE(zip_plus4, '')
);

-- Add comment for documentation
COMMENT ON TABLE public.standardized_addresses IS 'USPS standardized addresses cache';
