-- Copyright (c) 2026 Bob Hablutzel. All rights reserved.
--
-- Licensed under a dual-license model: freely available for non-commercial use;
-- commercial use requires a separate license. See LICENSE file for details.
-- Contact license@geastalt.com for commercial licensing.

-- Create contact_addresses table
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.contact_addresses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id    BIGINT NOT NULL REFERENCES public.contacts(id),
    address_id   BIGINT NOT NULL REFERENCES public.addresses(id),
    address_type VARCHAR(50) NOT NULL,
    CONSTRAINT uk_contact_address_type UNIQUE (contact_id, address_type)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_contact_addresses_contact_id ON public.contact_addresses(contact_id);
CREATE INDEX IF NOT EXISTS idx_contact_addresses_address_id ON public.contact_addresses(address_id);

-- Add comment for documentation
COMMENT ON TABLE public.contact_addresses IS 'Links contacts to their standardized addresses with address type';
