-- Create contact_emails table
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.contact_emails (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id  BIGINT NOT NULL REFERENCES public.contacts(id),
    email      VARCHAR(255) NOT NULL,
    email_type VARCHAR(50) NOT NULL,
    CONSTRAINT uk_contact_email_type UNIQUE (contact_id, email_type)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_contact_emails_contact_id ON public.contact_emails(contact_id);

-- Add comment for documentation
COMMENT ON TABLE public.contact_emails IS 'Stores contact email addresses with type (HOME, BUSINESS, MAILING)';
