-- Create contact_phones table
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.contact_phones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id    BIGINT NOT NULL REFERENCES public.contacts(id),
    phone_number VARCHAR(50) NOT NULL,
    phone_type   VARCHAR(50) NOT NULL,
    CONSTRAINT uk_contact_phone_type UNIQUE (contact_id, phone_type)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_contact_phones_contact_id ON public.contact_phones(contact_id);

-- Add comment for documentation
COMMENT ON TABLE public.contact_phones IS 'Stores contact phone numbers with type (HOME, BUSINESS, MAILING)';
