-- Create plans table for insurance/benefit plan definitions
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.plans (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name    VARCHAR(255) NOT NULL,
    carrier_id   INTEGER NOT NULL,
    carrier_name VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create index for carrier lookups
CREATE INDEX IF NOT EXISTS idx_plans_carrier_id ON public.plans(carrier_id);

-- Add comment for documentation
COMMENT ON TABLE public.plans IS 'Insurance/benefit plan definitions with carrier information';
