-- Create contact_plans table linking contacts to their plans
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.contact_plans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id       BIGINT NOT NULL REFERENCES public.contacts(id),
    plan_id         BIGINT NOT NULL REFERENCES public.plans(id),
    effective_date  TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_contact_plans_contact_id ON public.contact_plans(contact_id);
CREATE INDEX IF NOT EXISTS idx_contact_plans_plan_id ON public.contact_plans(plan_id);

-- Add comment for documentation
COMMENT ON TABLE public.contact_plans IS 'Links contacts to their insurance/benefit plans with effective date ranges';
