-- Copyright (c) 2026 Bob Hablutzel. All rights reserved.
--
-- Licensed under a dual-license model: freely available for non-commercial use;
-- commercial use requires a separate license. See LICENSE file for details.
-- Contact license@geastalt.com for commercial licensing.

-- Create contact_contracts table linking contacts to their contracts
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.contact_contracts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id      BIGINT NOT NULL REFERENCES public.contacts(id),
    contract_id     UUID NOT NULL REFERENCES public.contracts(id),
    effective_date  TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_contact_contracts_contact_id ON public.contact_contracts(contact_id);
CREATE INDEX IF NOT EXISTS idx_contact_contracts_contract_id ON public.contact_contracts(contract_id);

-- Add comment for documentation
COMMENT ON TABLE public.contact_contracts IS 'Links contacts to their contracts with effective date ranges';
