# Copyright (c) 2026 Bob Hablutzel. All rights reserved.
#
# Licensed under a dual-license model: freely available for non-commercial use;
# commercial use requires a separate license. See LICENSE file for details.
# Contact license@geastalt.com for commercial licensing.

spring:
  config:
    activate:
      on-profile: mysql

contact:
  sql:
    bulk:
      insert-address: >-
        INSERT INTO addresses (locality, administrative_area, postal_code, country_code)
        VALUES (?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)
