-- Create members table
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS member.members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS idx_members_email ON member.members(email);

-- Add comment for documentation
COMMENT ON TABLE member.members IS 'Member information table';
