-- Create member_addresses table
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.member_addresses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT NOT NULL REFERENCES public.members(id),
    address_id   BIGINT NOT NULL REFERENCES public.standardized_addresses(id),
    address_type VARCHAR(50) NOT NULL,
    CONSTRAINT uk_member_address_type UNIQUE (member_id, address_type)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_member_addresses_member_id ON public.member_addresses(member_id);
CREATE INDEX IF NOT EXISTS idx_member_addresses_address_id ON public.member_addresses(address_id);

-- Add comment for documentation
COMMENT ON TABLE public.member_addresses IS 'Links members to their standardized addresses with address type';
