-- Create member_emails table
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.member_emails (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT NOT NULL REFERENCES public.members(id),
    email      VARCHAR(255) NOT NULL,
    email_type VARCHAR(50) NOT NULL,
    CONSTRAINT uk_member_email_type UNIQUE (member_id, email_type)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_member_emails_member_id ON public.member_emails(member_id);

-- Add comment for documentation
COMMENT ON TABLE public.member_emails IS 'Stores member email addresses with type (HOME, BUSINESS, MAILING)';
