-- Create member_phones table
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.member_phones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT NOT NULL REFERENCES public.members(id),
    phone_number VARCHAR(50) NOT NULL,
    phone_type   VARCHAR(50) NOT NULL,
    CONSTRAINT uk_member_phone_type UNIQUE (member_id, phone_type)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_member_phones_member_id ON public.member_phones(member_id);

-- Add comment for documentation
COMMENT ON TABLE public.member_phones IS 'Stores member phone numbers with type (HOME, BUSINESS, MAILING)';
